### ISSUE TITLE
use firedoc to generate API documentation

### ISSUE THREAD

**Issue by yorkie** [weflex/semver-increment#9]
See the [example](https://github.com/weflex/pancake/blob/master/package.json#L34-L38) at [weflex/pancake](https://github.com/weflex/pancake).

We will have the following 3 things to be done:
- [x] update the doc comments in our source file: index.js
- [x] add firedoc config and scripts to generate documentation site
- [x] push it to the demo branch `gh-pages`.

Ping @jkvim

**Comment by jkvim** [comment]
@yorkie pong

**Comment by jkvim** [comment]
@yorkie firedoc is your repo, orz.

**Comment by yorkie** [comment]
..... commits please

**Comment by jkvim** [comment]
@yorkie do you know how to comment when the moudle.exports is a function like below code

``` javascript
/**
 * @module semver-increment
 */

/**
 * @param {String} a
 * @param {String} b
 */
module.exports = function(a, b) {

}
```

i have try like this but not work, can you give me some suggestion?

``` javascript
/**
 * @method main
 * @param {String} a
 * @param {String} b
 */

var main = module.exports = function(a, b) {
}
```
